---
version: 2
multicolumn: false
web-width: 800px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Rot_kmeans_inversion_40/Rot_kmeans_inversion_40.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336682/master/file/figures/Rot_kmeans_inversion_40/Rot_kmeans_inversion_40.png"
    folder_url: "/users/77845/articles/336682/master/folder/figures/Rot_kmeans_inversion_40"
