---
version: 2
multicolumn: false
web-width: 400px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Rot_bval_compartments/Rot_dets_compartments_w_mags_max-like_labels.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/349287/master/folder/figures/Rot_bval_compartments"
    url: "/users/77845/articles/349287/master/file/figures/Rot_bval_compartments/Rot_dets_compartments_w_mags_max-like_labels.png"
