---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Chamberfort_2014_fig3/Chamberfort_2014_fig3.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336675/master/file/figures/Chamberfort_2014_fig3/Chamberfort_2014_fig3.png"
    folder_url: "/users/77845/articles/336675/master/folder/figures/Chamberfort_2014_fig3"
