---
version: 2
multicolumn: false
web-width: 600px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/NgaN_ALL_flows_WHP/Ngatamariki_overview_Intro.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/336675/master/folder/figures/NgaN_ALL_flows_WHP"
    url: "/users/77845/articles/336675/master/file/figures/NgaN_ALL_flows_WHP/Ngatamariki_overview_Intro.png"
