---
version: 2
multicolumn: false
web-width: '600'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ORMAT_techs_overview/ORMAT_techs_overview.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336675/master/file/figures/ORMAT_techs_overview/ORMAT_techs_overview.png"
    folder_url: "/users/77845/articles/336675/master/folder/figures/ORMAT_techs_overview"
