---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/simple_stim_fig/simple_stim_fig.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336675/master/file/figures/simple_stim_fig/simple_stim_fig.png"
    folder_url: "/users/77845/articles/336675/master/folder/figures/simple_stim_fig"
