---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/merc_Nga_overview_temps-wells_12-15_no_inset/merc_Nga_overview_temps-wells_12-15_no_inset.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336675/master/file/figures/merc_Nga_overview_temps-wells_12-15_no_inset/merc_Nga_overview_temps-wells_12-15_no_inset.png"
    folder_url: "/users/77845/articles/336675/master/folder/figures/merc_Nga_overview_temps-wells_12-15_no_inset"
