---
version: 2
multicolumn: false
web-width: 600px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/merc_Rot_qtree_clust_cents_sigmas/merc_Rot_qtree_clust_cents_SHmax.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/336682/master/folder/figures/merc_Rot_qtree_clust_cents_sigmas"
    url: "/users/77845/articles/336682/master/file/figures/merc_Rot_qtree_clust_cents_sigmas/merc_Rot_qtree_clust_cents_SHmax.png"
