---
version: 2
multicolumn: false
web-width: 400px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/merc_Rot_dets_GC_boundaries/merc_Rot_dets_GC_boundaries_labs.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/349287/master/folder/figures/merc_Rot_dets_GC_boundaries"
    url: "/users/77845/articles/349287/master/file/figures/merc_Rot_dets_GC_boundaries/merc_Rot_dets_GC_boundaries_labs.png"
