---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/FMI_example_mod/FMI_example_mod.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336681/master/file/figures/FMI_example_mod/FMI_example_mod.png"
    folder_url: "/users/77845/articles/336681/master/folder/figures/FMI_example_mod"
