---
version: 2
multicolumn: false
web-width: 300px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Pf_increase_mohr/Pf_increase_mohr.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336675/master/file/figures/Pf_increase_mohr/Pf_increase_mohr.png"
    folder_url: "/users/77845/articles/336675/master/folder/figures/Pf_increase_mohr"
