---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/RotNga_catalog_overview/RotNga_catalog_overview.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/336681/master/folder/figures/RotNga_catalog_overview"
    url: "/users/77845/articles/336681/master/file/figures/RotNga_catalog_overview/RotNga_catalog_overview.png"
