---
version: 2
multicolumn: false
web-width: 700px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/merc_Nga_kmeans_10_GC_12-2-18/merc_Nga_kmeans_10_GC_12-2-18.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/336682/master/folder/figures/merc_Nga_kmeans_10_GC_12-2-18"
    url: "/users/77845/articles/336682/master/file/figures/merc_Nga_kmeans_10_GC_12-2-18/merc_Nga_kmeans_10_GC_12-2-18.png"
