---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Harris_2006_fig8/Harris_2006_fig8.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/77845/articles/336681/master/file/figures/Harris_2006_fig8/Harris_2006_fig8.png"
    folder_url: "/users/77845/articles/336681/master/folder/figures/Harris_2006_fig8"
