---
version: 2
multicolumn: false
web-width: 600px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/2D_003_sigmas/merc_Rot_2D_grid003_Arnold_clust_SHmax_nu.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/336682/master/folder/figures/2D_003_sigmas"
    url: "/users/77845/articles/336682/master/file/figures/2D_003_sigmas/merc_Rot_2D_grid003_Arnold_clust_SHmax_nu.png"
