---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Rot_swarms_thresh_30/Rot_swarms_thresh_30.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/349287/master/folder/figures/Rot_swarms_thresh_30"
    url: "/users/77845/articles/349287/master/file/figures/Rot_swarms_thresh_30/Rot_swarms_thresh_30.png"
