---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/NM08_stimulation_cartoon/NM08_stimulation_cartoon.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/325821/master/folder/figures/NM08_stimulation_cartoon"
    url: "/users/77845/articles/325821/master/file/figures/NM08_stimulation_cartoon/NM08_stimulation_cartoon.png"
