---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/merc_Nga_overview_temps-wells_12-15/merc_Nga_overview_wells_12-15.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/77845/articles/325821/master/folder/figures/merc_Nga_overview_temps-wells_12-15"
    url: "/users/77845/articles/325821/master/file/figures/merc_Nga_overview_temps-wells_12-15/merc_Nga_overview_wells_12-15.png"
